/* ENGLISH MONSTER ACADEMY — shared UI, sound and progress */
window.EMA={games:{},active:null};
(function(App){
 const defaults={score:0,stars:0,streak:0,completed:[],achievements:[],sound:true};
 const gameMeta={battle:{title:'MONSTER BATTLE',skill:'GRAMMAR',desc:'Answer grammar questions and defeat the Grammar Monster!',color:'#9a55ff',hue:'0deg',icon:'⚔️'},picture:{title:'PICTURE CHALLENGE',skill:'VOCABULARY',desc:'Look at the picture and choose the best word or phrase.',color:'#26dddc',hue:'80deg',icon:'🖼️'},sentence:{title:'SENTENCE LAB',skill:'SENTENCE BUILDING',desc:'Put the words in the correct order and create perfect sentences.',color:'#ff4db8',hue:'300deg',icon:'🧩'},rush:{title:'WORD RUSH',skill:'VOCABULARY + SPEED',desc:'Think fast! Choose the correct answer before time runs out.',color:'#77f35b',hue:'150deg',icon:'⚡'}};
 const helps={academy:{icon:'👾',title:'HOW TO PLAY',steps:['Choose one of the four monster challenges.','Complete ten B1 English tasks.','Earn points, stars and achievements.','Finish all challenges to become an English Master!']},battle:{icon:'⚔️',title:'MONSTER BATTLE',steps:['Read the English question.','Choose one answer.','A correct answer attacks the monster.','A wrong answer costs one heart.','Defeat the monster before you lose all your lives.']},picture:{icon:'🖼️',title:'PICTURE CHALLENGE',steps:['Study the picture carefully.','Choose the best word or phrase.','Read the explanation after answering.','Finish ten pictures before losing three lives.']},sentence:{icon:'🧩',title:'SENTENCE LAB',steps:['Click the words in the correct order.','Use Backspace, Clear or Hint if needed.','Press Check to test your sentence.','You have three attempts for each sentence.']},rush:{icon:'⚡',title:'WORD RUSH',steps:['Read the vocabulary question.','Answer before the ten-second timer ends.','Fast answers earn more points.','Complete ten questions to win.']}};
 const achievements={first:{icon:'⭐',name:'FIRST WIN',text:'Complete your first challenge.'},streak:{icon:'🔥',name:'HOT STREAK',text:'Get 5 correct answers in a row.'},hunter:{icon:'👾',name:'MONSTER HUNTER',text:'Defeat the Grammar Monster.'},speed:{icon:'⚡',name:'SPEED MASTER',text:'Complete Word Rush.'},sentence:{icon:'🧩',name:'SENTENCE MASTER',text:'Complete Sentence Lab.'},master:{icon:'🏆',name:'ENGLISH MASTER',text:'Complete all four games.'}};
 App.progress=load(); App.meta=gameMeta;
 function load(){try{return {...defaults,...JSON.parse(localStorage.getItem('ema-progress'))}}catch(e){return {...defaults}}}
 App.save=function(){localStorage.setItem('ema-progress',JSON.stringify(App.progress));updateStats();renderAchievements()};
 App.addScore=function(n){App.progress.score+=n;App.save();pop('#stat-score')};
 App.correct=function(points){App.addScore(points);App.progress.streak++;if(App.progress.streak>=5)unlock('streak');App.save()};
 App.wrong=function(){App.progress.streak=0;App.save()};
 App.complete=function(id,stars){if(!App.progress.completed.includes(id)){App.progress.completed.push(id);App.progress.stars+=stars}unlock('first');if(id==='battle')unlock('hunter');if(id==='rush')unlock('speed');if(id==='sentence')unlock('sentence');if(App.progress.completed.length===4)unlock('master');App.save()};
 function unlock(id){if(!App.progress.achievements.includes(id)){App.progress.achievements.push(id);App.toast('🏅 NEW ACHIEVEMENT: '+achievements[id].name)}}
 function updateStats(){q('#stat-score').textContent=App.progress.score;q('#stat-stars').textContent=App.progress.stars;q('#stat-streak').textContent=App.progress.streak;q('#stat-completed').textContent=App.progress.completed.length+'/4';document.querySelectorAll('.sound-toggle').forEach(b=>b.innerHTML=(App.progress.sound?'🔊 <span>SOUND ON</span>':'🔇 <span>SOUND OFF</span>'))}
 function renderCards(){q('#game-grid').innerHTML=Object.entries(gameMeta).map(([id,g])=>`<article class="game-card" style="--accent:${g.color};--hue:${g.hue}"><img src="images/${id==='battle'?'grammar-monster':id==='picture'?'picture-monster':id==='sentence'?'sentence-monster':'speed-monster'}.png" alt="${g.title} neon monster"><div class="skill">${g.skill}</div><h3>${g.title}</h3><p>${g.desc}</p><div class="card-meta"><span>LEVEL B1</span><b>${App.progress.completed.includes(id)?'✓ COMPLETE':'B1'}</b></div><div class="card-actions"><button class="btn primary" data-play="${id}">PLAY</button><button class="icon-btn" data-help="${id}" aria-label="How to play ${g.title}">?</button></div></article>`).join('')}
 function renderAchievements(){q('#achievement-grid').innerHTML=Object.entries(achievements).map(([id,a])=>`<article class="achievement ${App.progress.achievements.includes(id)?'unlocked':''}"><span>${a.icon}</span><div><h3>${a.name}</h3><p>${a.text}</p></div></article>`).join('');renderCards()}
 App.openHelp=function(id){let h=helps[id];q('#modal-content').innerHTML=`<div class="big-icon">${h.icon}</div><h2>${h.title}</h2><ol>${h.steps.map(x=>`<li>${x}</li>`).join('')}</ol><button class="btn primary modal-done">GOT IT!</button>`;q('#modal').classList.add('show');q('#modal').setAttribute('aria-hidden','false')};
 function closeModal(){q('#modal').classList.remove('show');q('#modal').setAttribute('aria-hidden','true')}
 App.openGame=function(id){App.active=id;let g=gameMeta[id];q('#game-content').innerHTML=`<section class="game-stage game-start"><img src="images/${id==='battle'?'grammar-monster':id==='picture'?'picture-monster':id==='sentence'?'sentence-monster':'speed-monster'}.png" alt="${g.title} monster"><span class="eyebrow">${g.skill} • LEVEL B1</span><h2>${g.title}</h2><p>${g.desc}</p><div class="actions" style="justify-content:center"><button class="btn primary" id="start-game">START CHALLENGE</button><button class="btn ghost" data-help="${id}">HOW TO PLAY</button><button class="btn ghost close-game">BACK</button></div></section>`;q('#game-shell').classList.add('show');q('#game-shell').setAttribute('aria-hidden','false');document.body.style.overflow='hidden';q('#start-game').onclick=()=>App.games[id].start()};
 App.closeGame=function(){if(App.games[App.active]?.stop)App.games[App.active].stop();q('#game-shell').classList.remove('show');q('#game-shell').setAttribute('aria-hidden','true');document.body.style.overflow='';renderAchievements()};
 App.result=function(id,score,correct,total,won=true){let stars=correct>=9?3:correct>=7?2:1;if(won)App.complete(id,stars);q('#game-content').innerHTML=`<section class="game-stage result">${won?'<div class="confetti" aria-hidden="true"><i>★</i><i>✦</i><i>★</i><i>✦</i><i>★</i></div>':''}<img src="images/victory-monster.png" alt="Happy victory monster"><span class="eyebrow">${won?'MONSTER DEFEATED':'CHALLENGE FAILED'}</span><h2>${won?(id==='battle'?'MONSTER DEFEATED!':'CHALLENGE COMPLETE!'):'GAME OVER'}</h2><p>${won?'Amazing work! Your English power is growing.':'The monster won this round. Ready for another battle?'}</p><div class="hud"><div><span>Round score</span><strong>${score}</strong></div><div><span>Accuracy</span><strong>${Math.round(correct/total*100)}%</strong></div><div><span>Stars</span><strong>${won?'⭐'.repeat(stars):'0'}</strong></div><div><span>Correct answers</span><strong>${correct}/${total}</strong></div></div><div class="actions" style="justify-content:center">${won&&nextId(id)?'<button class="btn primary" id="next-game">NEXT CHALLENGE</button>':''}<button class="btn ${won?'ghost':'primary'}" id="replay">${won?'PLAY AGAIN':'TRY AGAIN'}</button><button class="btn ghost close-game">BACK TO GAMES</button></div></section>`;q('#replay').onclick=()=>App.games[id].start();if(q('#next-game'))q('#next-game').onclick=()=>App.openGame(nextId(id));sound(won?'victory':'game-over');if(App.progress.completed.length===4)setTimeout(masterScreen,700)};
 function masterScreen(){q('#modal-content').innerHTML=`<div class="master-stars" aria-hidden="true">★ ✦ ★</div><div class="big-icon">🏆</div><h2>🏆 ENGLISH MASTER 🏆</h2><p style="text-align:center">Congratulations! You completed every challenge in the English Monster Academy!</p><div class="hud"><div><span>Total score</span><strong>${App.progress.score}</strong></div><div><span>Games completed</span><strong>4/4</strong></div><div><span>Total stars</span><strong>${App.progress.stars}</strong></div><div><span>Rank</span><strong>MASTER</strong></div></div><div class="actions"><button class="btn primary" id="master-replay">PLAY AGAIN</button><button class="btn ghost modal-done">BACK TO ACADEMY</button></div>`;q('#modal').classList.add('show');q('#modal').setAttribute('aria-hidden','false');q('#master-replay').onclick=()=>{closeModal();App.openGame('battle')}}
 function nextId(id){let ids=Object.keys(gameMeta),n=ids.indexOf(id)+1;return ids[n]||null}
 App.shuffle=a=>[...a].sort(()=>Math.random()-.5);App.pick=(a,n=10)=>App.shuffle(a).slice(0,n);App.positive=()=>App.pick(['Awesome!','Great job!','Perfect!','Monster hit!','Excellent!','Nice one!',"You're on fire!"],1)[0];App.negative=()=>App.pick(['Almost!','Try again!','Watch out!','Not quite!','Keep going!'],1)[0];
 App.toast=function(msg){let t=q('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(App.toastTimer);App.toastTimer=setTimeout(()=>t.classList.remove('show'),2200)};
 let audioCtx,drone;
 function synth(name){audioCtx=audioCtx||new (window.AudioContext||window.webkitAudioContext)();let o=audioCtx.createOscillator(),g=audioCtx.createGain(),good=['correct','victory'].includes(name);o.type=good?'sine':'square';o.frequency.setValueAtTime(good?520:name==='wrong'?150:260,audioCtx.currentTime);if(good)o.frequency.exponentialRampToValueAtTime(820,audioCtx.currentTime+.16);g.gain.setValueAtTime(.045,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+.22);o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+.23)}
 function sound(name){if(App.progress.sound)synth(name)}App.sound=sound;
 function toggleDrone(on){if(!on&&drone){drone.stop();drone=null;return}if(on&&!drone){audioCtx=audioCtx||new (window.AudioContext||window.webkitAudioContext)();let o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='sine';o.frequency.value=82;g.gain.value=.012;o.connect(g).connect(audioCtx.destination);o.start();drone=o}}
 function q(s){return document.querySelector(s)}function pop(s){q(s).animate([{transform:'scale(1)'},{transform:'scale(1.35)',color:'#77f35b'},{transform:'scale(1)'}],300)}
 document.addEventListener('click',e=>{let p=e.target.closest('[data-play]'),h=e.target.closest('[data-help]');if(e.target.closest('.btn,.icon-btn,.nav-toggle,.text-btn,.modal-x,.game-close')&&!e.target.closest('.answer,#check,.sound-toggle'))sound('click');if(p)App.openGame(p.dataset.play);if(h)App.openHelp(h.dataset.help);if(e.target.closest('.modal-x,.modal-done'))closeModal();if(e.target.closest('.game-close,.close-game'))App.closeGame();if(e.target.closest('.sound-toggle')){App.progress.sound=!App.progress.sound;App.save();toggleDrone(App.progress.sound)}});
 q('#modal').addEventListener('click',e=>{if(e.target===q('#modal'))closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeModal();if(q('#game-shell').classList.contains('show'))App.closeGame()}});q('.nav-toggle').onclick=()=>q('.topbar nav').classList.toggle('open');q('#reset-progress').onclick=()=>{q('#modal-content').innerHTML='<div class="big-icon">♻️</div><h2>RESET PROGRESS?</h2><p style="text-align:center">Your score, stars and achievements will be cleared.</p><div class="actions"><button class="btn primary" id="confirm-reset">RESET</button><button class="btn ghost modal-done">CANCEL</button></div>';q('#modal').classList.add('show');q('#modal').setAttribute('aria-hidden','false');setTimeout(()=>q('#confirm-reset').onclick=()=>{App.progress={...defaults};App.save();closeModal()},0)};
 document.addEventListener('pointerdown',()=>{if(App.progress.sound)toggleDrone(true)},{once:true});
 document.querySelectorAll('img').forEach(img=>img.addEventListener('error',()=>{img.hidden=true;let p=document.createElement('div');p.className='scene';p.textContent='👾';p.setAttribute('aria-label',img.alt);img.after(p)}));updateStats();renderAchievements();
})(window.EMA);
