/* SENTENCE LAB LOGIC */
(function(App){const bank=[
{s:'Have you ever visited London?',w:['Have','you','ever','visited','London','?'],h:'Present Perfect question: Have + subject + past participle.'},
{s:'If I had more time, I would travel more.',w:['If','I','had','more','time,','I','would','travel','more.'],h:'This is the second conditional.'},
{s:'You should talk to your teacher about the problem.',w:['You','should','talk','to','your','teacher','about','the','problem.'],h:'Put should before the main verb.'},
{s:'This is the book that I told you about.',w:['This','is','the','book','that','I','told','you','about.'],h:'The relative clause comes after book.'},
{s:'I have never tried Japanese food.',w:['I','have','never','tried','Japanese','food.'],h:'Never goes between have and the past participle.'},
{s:'How long have you lived here?',w:['How','long','have','you','lived','here','?'],h:'Start with How long, then use Present Perfect.'},
{s:'We were watching TV when the lights went out.',w:['We','were','watching','TV','when','the','lights','went','out.'],h:'Use Past Continuous for the longer action.'},
{s:'If it rains tomorrow, we will stay at home.',w:['If','it','rains','tomorrow,','we','will','stay','at','home.'],h:'First conditional: present after if, then will.'},
{s:'The new sports centre was opened last month.',w:['The','new','sports','centre','was','opened','last','month.'],h:'This sentence is in the passive voice.'},
{s:'Could you tell me where the station is?',w:['Could','you','tell','me','where','the','station','is','?'],h:'In an indirect question, use statement word order.'},
{s:'She decided to join the drama club.',w:['She','decided','to','join','the','drama','club.'],h:'Decide is followed by to + infinitive.'},
{s:'That is the girl whose brother won the race.',w:['That','is','the','girl','whose','brother','won','the','race.'],h:'Whose shows possession.'},
{s:'I am looking forward to seeing you.',w:['I','am','looking','forward','to','seeing','you.'],h:'Looking forward to is followed by -ing.'},
{s:'You do not have to bring any food.',w:['You','do','not','have','to','bring','any','food.'],h:'Do not have to means it is not necessary.'}
];
App.games.sentence={start(){let round=App.pick(bank,10),i=0,correct=0,score=0,attempts=0,selected=[],order=[];const root=document.querySelector('#game-content');
 function render(){selected=[];attempts=0;order=App.shuffle(round[i].w.map((v,n)=>({v,n})));draw()}
 function draw(message=''){root.innerHTML=`<section class="game-stage"><div class="hud"><div><span>Score</span><strong>${score}</strong></div><div><span>Sentence</span><strong>${i+1} / 10</strong></div><div><span>Attempts</span><strong>${3-attempts}</strong></div><div><span>Streak</span><strong>x${App.progress.streak}</strong></div></div><div class="progress"><i style="width:${i*10}%"></i></div><div class="question-box" style="margin-top:20px;text-align:center"><span class="eyebrow">BUILD THE PERFECT SENTENCE</span><h2>Put the words in the correct order.</h2><div class="sentence-area">${selected.map((x,j)=>`<button class="tile" data-remove="${j}">${x.v}</button>`).join('')}</div><div class="tiles">${order.map((x,j)=>`<button class="tile ${selected.includes(x)?'used':''}" data-tile="${j}">${x.v}</button>`).join('')}</div><div class="feedback">${message}</div><div class="actions" style="justify-content:center"><button class="btn primary" id="check">CHECK</button><button class="btn ghost" id="backspace">BACKSPACE</button><button class="btn ghost" id="clear">CLEAR</button><button class="btn ghost" id="hint">HINT</button></div></div></section>`;root.querySelectorAll('[data-tile]').forEach(b=>b.onclick=()=>{selected.push(order[+b.dataset.tile]);draw()});root.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{selected.splice(+b.dataset.remove,1);draw()});root.querySelector('#backspace').onclick=()=>{selected.pop();draw()};root.querySelector('#clear').onclick=()=>{selected=[];draw()};root.querySelector('#hint').onclick=()=>{let target=round[i].w[selected.length],match=order.find(x=>x.v===target&&!selected.includes(x));if(match)selected.push(match);draw('💡 '+round[i].h)};root.querySelector('#check').onclick=check}
 function check(){let answer=selected.map(x=>x.v).join(' ').replace(' ?','?'),ok=answer===round[i].s;if(ok){let pts=Math.max(60,120-attempts*20);score+=pts;correct++;App.correct(pts);App.sound('correct');draw('<b>Perfect sentence!</b>');setTimeout(next,850)}else{attempts++;App.wrong();App.sound('wrong');if(attempts>=3){draw(`<b>Correct sentence:</b> ${round[i].s}`);setTimeout(next,1600)}else draw(`<b>${App.negative()}</b> ${round[i].h}`)}}function next(){i++;if(i>=10)App.result('sentence',score,correct,10,true);else render()}render()},stop(){}};
})(window.EMA);
