/* SENTENCE LAB LOGIC */
(function(App){const bank=[
{s:'Have you ever visited London?',w:['Have','you','ever','visited','London','?'],h:'Present Perfect question: Have + subject + past participle.'},
{s:'If I had more time, I would travel more.',w:['If','I','had','more','time,','I','would','travel','more.'],h:'This is the second conditional.'},
{s:'You should talk to your teacher about the problem.',w:['You','should','talk','to','your','teacher','about','the','problem.'],h:'Put should before the main verb.'},
{s:'This is the book that I told you about.',w:['This','is','the','book','that','I','told','you','about.'],h:'The relative clause comes after book.'},
{s:'I have never tried Japanese food.',w:['I','have','never','tried','Japanese','food.'],h:'Never goes between have and the past participle.'},
{s:'How long have you lived here?',w:['How','long','have','you','lived','here','?'],h:'Start with How long, then use Present Perfect.'},
{s:'We were watching TV when the lights went out.',w:['We','were','watching','TV','when','the','lights','went','out.'],h:'Use Past Continuous for the longer action.'},
{s:'If it rains tomorrow, we will stay at home.',w:['If','it','rains','tomorrow,','we','will','stay','at','home.'],h:'First conditional: present after if, then will.'},
{s:'The new sports centre was opened last month.',w:['The','new','sports','centre','was','opened','last','month.'],h:'This sentence is in the passive voice.'},
{s:'Could you tell me where the station is?',w:['Could','you','tell','me','where','the','station','is','?'],h:'In an indirect question, use statement word order.'},
{s:'She decided to join the drama club.',w:['She','decided','to','join','the','drama','club.'],h:'Decide is followed by to + infinitive.'},
{s:'That is the girl whose brother won the race.',w:['That','is','the','girl','whose','brother','won','the','race.'],h:'Whose shows possession.'},
{s:'I am looking forward to seeing you.',w:['I','am','looking','forward','to','seeing','you.'],h:'Looking forward to is followed by -ing.'},
{s:'You do not have to bring any food.',w:['You','do','not','have','to','bring','any','food.'],h:'Do not have to means it is not necessary.'}
];
App.games.sentence={start(){let round=App.pick(bank,10),i=0,correct=0,score=0,attempts=0,selected=[],order=[],locked=false,hints=0;const root=document.querySelector('#game-content');
 function render(){selected=[];attempts=0;hints=0;locked=false;order=App.shuffle(round[i].w.map((v,n)=>({v,n})));draw()}
 function draw(feedback=null){root.innerHTML=`<section class="game-stage"><div class="hud"><div><span>Score</span><strong>${score}</strong></div><div><span>Sentence</span><strong>${i+1} / 10</strong></div><div><span>Attempts</span><strong>${Math.max(0,3-attempts)}</strong></div><div><span>Streak</span><strong>x${App.progress.streak}</strong></div></div><div class="progress"><i style="width:${i*10}%"></i></div><div class="question-box" style="margin-top:20px;text-align:center"><span class="eyebrow">BUILD THE PERFECT SENTENCE</span><h2>Put the words in the correct order.</h2><div class="sentence-area ${feedback?.type||''}">${selected.map((x,j)=>`<button class="tile" data-remove="${j}" ${locked?'disabled':''}>${x.v}</button>`).join('')}</div><div class="tiles">${order.map((x,j)=>`<button class="tile ${selected.includes(x)?'used':''}" data-tile="${j}" ${locked?'disabled':''}>${x.v}</button>`).join('')}</div>${feedback?`<div class="feedback-panel ${feedback.type}" aria-live="polite"><strong>${feedback.title}</strong><p>${feedback.text}</p>${feedback.next?'<button class="btn primary" id="next-sentence">NEXT SENTENCE →</button>':''}</div>`:'<div class="feedback-panel hint-panel" aria-live="polite" hidden></div>'}<div class="actions" style="justify-content:center"><button class="btn primary" id="check" ${locked?'disabled':''}>CHECK</button><button class="btn ghost" id="backspace" ${locked?'disabled':''}>BACKSPACE</button><button class="btn ghost" id="clear" ${locked?'disabled':''}>CLEAR</button><button class="btn ghost" id="hint" ${locked?'disabled':''}>HINT</button></div></div></section>`;root.querySelectorAll('[data-tile]').forEach(b=>b.onclick=()=>{selected.push(order[+b.dataset.tile]);draw()});root.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{selected.splice(+b.dataset.remove,1);draw()});root.querySelector('#backspace').onclick=()=>{selected.pop();draw()};root.querySelector('#clear').onclick=()=>{selected=[];draw()};root.querySelector('#hint').onclick=hint;root.querySelector('#check').onclick=check;root.querySelector('#next-sentence')?.addEventListener('click',next)}
 function hint(){hints++;if(hints===1&&selected.length===0){let first=round[i].w[0],match=order.find(x=>x.v===first&&!selected.includes(x));if(match)selected.push(match);draw({type:'hint',title:'First word revealed',text:`Start with “${first}”.`,next:false})}else draw({type:'hint',title:'Grammar clue',text:round[i].h,next:false})}
 function check(){if(locked)return;let answer=selected.map(x=>x.v).join(' ').replace(' ?','?'),ok=answer===round[i].s;if(ok){locked=true;let pts=Math.max(60,120-attempts*20);score+=pts;correct++;App.correct(pts);App.sound('correct');draw({type:'success',title:'Perfect sentence!',text:round[i].h,next:true})}else{attempts++;App.wrong();App.sound('wrong');if(attempts>=3){locked=true;selected=round[i].w.map((v,n)=>({v,n}));draw({type:'success',title:'Correct sentence:',text:`${round[i].s} ${round[i].h}`,next:true})}else draw({type:'error',title:'Almost! Try again.',text:`Check the word order. ${round[i].h}`,next:false})}}
 function next(){if(!locked)return;i++;if(i>=10)App.result('sentence',score,correct,10,true);else render()}render()},stop(){}};
})(window.EMA);
