/* WORD RUSH LOGIC */
(function(App){const bank=[
['Choose the synonym of “exhausted”.',['excited','very tired','surprised','hungry'],1,'Exhausted means extremely tired.'],['Choose the opposite of “generous”.',['selfish','patient','honest','cheerful'],0,'A selfish person does not like sharing.'],['What does “give up” mean?',['continue','stop trying','return','invent'],1,'Give up means stop doing or trying something.'],['Complete: “___ a decision.”',['do','make','take','get'],1,'We say make a decision.'],['The flight was ___ because of fog.',['delayed','borrowed','escaped','uploaded'],0,'Delayed means made to happen later.'],['Choose the synonym of “reliable”.',['dependable','careless','ordinary','rude'],0,'You can trust a reliable person.'],['Choose the opposite of “crowded”.',['ancient','empty','noisy','narrow'],1,'An empty place has few or no people.'],['What does “look after” mean?',['search for','take care of','admire','wait for'],1,'Look after means take care of someone or something.'],['Complete: “pay ___ to the instructions.”',['notice','attention','interest','care'],1,'The collocation is pay attention.'],['Someone who feels “disappointed” is ___.',['sad because hopes failed','angry for no reason','full of energy','unable to speak'],0,'Disappointed describes sadness when something was worse than hoped.'],['You should ___ your files before updating.',['back up','break down','turn down','log out'],0,'Back up means make a safe copy.'],['Choose the synonym of “purchase”.',['sell','borrow','buy','repair'],2,'Purchase is a more formal word for buy.'],['Complete: “keep in ___ with old friends.”',['contact','touch','talk','meeting'],1,'The phrase is keep in touch.'],['A “destination” is ___.',['the place you travel to','a travel document','a type of luggage','a delay'],0,'A destination is the place at the end of a journey.'],['Choose the opposite of “temporary”.',['modern','permanent','regular','recent'],1,'Permanent means lasting for a long time.'],['What does “find out” mean?',['discover information','lose an object','create a plan','meet by chance'],0,'Find out means discover or learn a fact.'],['Complete: “She ___ an exam yesterday.”',['made','took','played','gave'],1,'Students take an exam.'],['A person who is “confident” ___.',['believes in their ability','gets angry easily','avoids all people','cannot decide'],0,'Confidence means belief in yourself.'],['Choose the synonym of “improve”.',['reduce','avoid','make better','replace'],2,'Improve means make or become better.'],['What does “get along with” mean?',['have a good relationship with','travel together','disagree with','teach someone'],0,'Get along with means have a friendly relationship.'],['Choose the opposite of “polite”.',['patient','rude','quiet','formal'],1,'Rude is the opposite of polite.'],['Complete: “do ___ online.”',['research','a research','searches','an information'],0,'Research is uncountable here: do research.']
].map(x=>({q:x[0],a:x[1],c:x[2],e:x[3]}));
App.games.rush={timer:null,start(){let round=App.pick(bank,10),i=0,lives=3,correct=0,score=0,time=10,locked=false,root=document.querySelector('#game-content');
 const stop=()=>{clearInterval(App.games.rush.timer)};this.stop=stop;
 function render(){stop();time=10;locked=false;let x=round[i];root.innerHTML=`<section class="game-stage"><div class="hud"><div><span>Score</span><strong>${score}</strong></div><div><span>Question</span><strong>${i+1} / 10</strong></div><div><span>Lives</span><strong>${'❤️'.repeat(lives)||'—'}</strong></div><div><span>Bonus</span><strong>UP TO +150</strong></div></div><div class="timer" style="--time:100%">10</div><div class="question-box"><span class="eyebrow">THINK FAST!</span><h2>${x.q}</h2><div class="answers">${x.a.map((a,n)=>`<button class="answer" data-answer="${n}"><b>${String.fromCharCode(65+n)}.</b> ${a}</button>`).join('')}</div><div class="feedback"></div></div></section>`;root.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>answer(+b.dataset.answer));App.games.rush.timer=setInterval(()=>{time--;let t=root.querySelector('.timer');if(!t)return stop();t.textContent=time;t.style.setProperty('--time',time*10+'%');if(time<=0)timeout()},1000)}
 function answer(n){if(locked)return;locked=true;stop();let x=round[i],ok=n===x.c,bs=[...root.querySelectorAll('[data-answer]')];bs[n].classList.add(ok?'correct':'wrong');bs[x.c].classList.add('correct');if(ok){let pts=time>=7?150:time>=4?100:50;score+=pts;correct++;App.correct(pts);App.sound('correct');root.querySelector('.feedback').innerHTML=`<b>${App.positive()} +${pts}</b> ${x.e}`}else{lives--;App.wrong();App.sound('wrong');root.querySelector('.feedback').innerHTML=`<b>${App.negative()}</b> ${x.e}`}setTimeout(next,1100)}
 function timeout(){if(locked)return;locked=true;stop();lives--;App.wrong();App.sound('wrong');let x=round[i];root.querySelectorAll('[data-answer]')[x.c].classList.add('correct');root.querySelector('.feedback').innerHTML=`<b>Time's up!</b> ${x.e}`;setTimeout(next,1200)}function next(){i++;if(lives<=0)return App.result('rush',score,correct,10,false);if(i>=10)return App.result('rush',score,correct,10,true);render()}render()}};
})(window.EMA);
