/* WORD RUSH LOGIC */
(function(App){const bank=[
['Choose the synonym of “exhausted”.',['excited','very tired','surprised','hungry'],1,'Exhausted means extremely tired.'],['Choose the opposite of “generous”.',['selfish','patient','honest','cheerful'],0,'A selfish person does not like sharing.'],['What does “give up” mean?',['continue','stop trying','return','invent'],1,'Give up means stop doing or trying something.'],['Complete: “___ a decision.”',['do','make','take','get'],1,'We say make a decision.'],['The flight was ___ because of fog.',['delayed','borrowed','escaped','uploaded'],0,'Delayed means made to happen later.'],['Choose the synonym of “reliable”.',['dependable','careless','ordinary','rude'],0,'You can trust a reliable person.'],['Choose the opposite of “crowded”.',['ancient','empty','noisy','narrow'],1,'An empty place has few or no people.'],['What does “look after” mean?',['search for','take care of','admire','wait for'],1,'Look after means take care of someone or something.'],['Complete: “pay ___ to the instructions.”',['notice','attention','interest','care'],1,'The collocation is pay attention.'],['Someone who feels “disappointed” is ___.',['sad because hopes failed','angry for no reason','full of energy','unable to speak'],0,'Disappointed describes sadness when something was worse than hoped.'],['You should ___ your files before updating.',['back up','break down','turn down','log out'],0,'Back up means make a safe copy.'],['Choose the synonym of “purchase”.',['sell','borrow','buy','repair'],2,'Purchase is a more formal word for buy.'],['Complete: “keep in ___ with old friends.”',['contact','touch','talk','meeting'],1,'The phrase is keep in touch.'],['A “destination” is ___.',['the place you travel to','a travel document','a type of luggage','a delay'],0,'A destination is the place at the end of a journey.'],['Choose the opposite of “temporary”.',['modern','permanent','regular','recent'],1,'Permanent means lasting for a long time.'],['What does “find out” mean?',['discover information','lose an object','create a plan','meet by chance'],0,'Find out means discover or learn a fact.'],['Complete: “She ___ an exam yesterday.”',['made','took','played','gave'],1,'Students take an exam.'],['A person who is “confident” ___.',['believes in their ability','gets angry easily','avoids all people','cannot decide'],0,'Confidence means belief in yourself.'],['Choose the synonym of “improve”.',['reduce','avoid','make better','replace'],2,'Improve means make or become better.'],['What does “get along with” mean?',['have a good relationship with','travel together','disagree with','teach someone'],0,'Get along with means have a friendly relationship.'],['Choose the opposite of “polite”.',['patient','rude','quiet','formal'],1,'Rude is the opposite of polite.'],['Complete: “do ___ online.”',['research','a research','searches','an information'],0,'Research is uncountable here: do research.']
].map(x=>({q:x[0],a:x[1],c:x[2],e:x[3]}));
App.games.rush={timer:null,transition:null,start(){let round=App.pick(bank,10),i=0,lives=3,correct=0,score=0,time=10,locked=false,root=document.querySelector('#game-content'),keyHandler;
 const stop=()=>{clearInterval(App.games.rush.timer);clearTimeout(App.games.rush.transition);App.games.rush.timer=null;App.games.rush.transition=null;document.removeEventListener('keydown',keyHandler)};this.stop=stop;
 function render(){clearInterval(App.games.rush.timer);clearTimeout(App.games.rush.transition);time=10;locked=false;let x=round[i];root.innerHTML=`<section class="game-stage"><div class="hud"><div><span>Score</span><strong id="rush-score">${score}</strong></div><div><span>Question</span><strong>${i+1} / 10</strong></div><div><span>Lives</span><strong>${'❤️'.repeat(lives)||'—'}</strong></div><div><span>Bonus</span><strong>UP TO +150</strong></div></div><div class="timer" style="--time:100%" aria-label="10 seconds remaining">10</div><div class="question-box"><span class="eyebrow">THINK FAST!</span><h2>${x.q}</h2><div class="answers">${x.a.map((a,n)=>`<button class="answer" data-answer="${n}" aria-label="Answer ${n+1}: ${a}"><b>${String.fromCharCode(65+n)}.</b> ${a}</button>`).join('')}</div><div class="feedback-panel rush-feedback" aria-live="polite" hidden></div></div></section>`;root.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>answer(+b.dataset.answer));App.games.rush.timer=setInterval(()=>{time--;let t=root.querySelector('.timer');if(!t)return clearInterval(App.games.rush.timer);t.textContent=time;t.setAttribute('aria-label',`${time} seconds remaining`);t.style.setProperty('--time',time*10+'%');t.classList.toggle('warning',time<=6&&time>3);t.classList.toggle('urgent',time<=3);if(time<=0)timeout()},1000)}
 function lockAnswers(){root.querySelectorAll('[data-answer]').forEach(b=>b.disabled=true)}
 function showFeedback(type,title,text){let panel=root.querySelector('.feedback-panel');panel.hidden=false;panel.className=`feedback-panel rush-feedback ${type}`;panel.innerHTML=`<strong>${title}</strong><p>${text}</p>`}
 function answer(n){if(locked)return;locked=true;clearInterval(App.games.rush.timer);App.games.rush.timer=null;lockAnswers();let x=round[i],ok=n===x.c,bs=[...root.querySelectorAll('[data-answer]')];bs[n].classList.add(ok?'correct':'wrong');bs[x.c].classList.add('correct');if(ok){let pts=time>=7?150:time>=4?100:50;score+=pts;correct++;App.correct(pts);App.sound('correct');root.querySelector('#rush-score').textContent=score;root.querySelector('#rush-score').classList.add('score-burst');showFeedback('success',`${App.positive()} +${pts}`,pts===150?'SPEED BONUS! '+x.e:x.e)}else{lives--;App.wrong();App.sound('wrong');showFeedback('error',App.negative(),`The correct answer is ${x.a[x.c]}. ${x.e}`)}App.games.rush.transition=setTimeout(next,1800)}
 function timeout(){if(locked)return;locked=true;clearInterval(App.games.rush.timer);App.games.rush.timer=null;lockAnswers();lives--;App.wrong();App.sound('wrong');let x=round[i];root.querySelectorAll('[data-answer]')[x.c].classList.add('correct');showFeedback('error',"TIME'S UP!",`The correct answer is ${x.a[x.c]}. ${x.e}`);App.games.rush.transition=setTimeout(next,2000)}
 function next(){clearTimeout(App.games.rush.transition);i++;if(lives<=0){stop();return App.result('rush',score,correct,10,false)}if(i>=10){stop();return App.result('rush',score,correct,10,true)}render()}
 keyHandler=e=>{if(e.target.matches('input,textarea,select'))return;if(!locked&&['1','2','3','4'].includes(e.key))root.querySelector(`[data-answer="${+e.key-1}"]`)?.click()};document.addEventListener('keydown',keyHandler);render()}};
})(window.EMA);
